"""rename department

Revision ID: <your_revision_id>
Revises: <previous_revision_id>
Create Date: <date>

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '<your_revision_id>'
down_revision = '<previous_revision_id>'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###



# """rename department

# Revision ID: 52fdc383cccf
# Revises: 0c3f0abd890e
# Create Date: 2024-06-29 19:51:51.982889

# """
# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision = '52fdc383cccf'
# down_revision = '0c3f0abd890e'
# branch_labels = None
# depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('departments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('address', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('department')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('department',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('name', sa.VARCHAR(), nullable=False),
#     sa.Column('address', sa.VARCHAR(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('departments')
#     # ### end Alembic commands ###
